# Generated by Django 3.0.7 on 2020-07-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=9, verbose_name='Period')),
                ('title', models.CharField(max_length=100, verbose_name='Title/Award')),
                ('enterprise', models.CharField(max_length=100, verbose_name='Enterprise')),
                ('description', models.TextField(verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=9, verbose_name='Period')),
                ('title', models.CharField(max_length=100, verbose_name='Title/Grade')),
                ('school', models.CharField(max_length=100, verbose_name='School')),
                ('description', models.TextField(verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=9, verbose_name='Period')),
                ('title', models.CharField(max_length=100, verbose_name='Title/Job')),
                ('enterprise', models.CharField(max_length=100, verbose_name='Enterprise')),
                ('description', models.TextField(verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
